name: CI with Verilator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator g++ make
        sudo apt-get install git help2man perl python3 make
        sudo apt-get install libfl2
        sudo apt-get install libfl-dev
        sudo apt-get install zlibc zlib1g zlib1g-dev
        sudo apt-get install ccache
        sudo apt-get install mold
        sudo apt-get install libgoogle-perftools-dev numactl
        sudo apt-get install perl-doc
        sudo apt-get install git autoconf flex bison


    - name: all files lint only
      run: |
        verilator --lint-only device.sv tb.sv
        # Compile the Verilog/SystemVerilog code with Verilator
        # verilator --cc --trace --build src/my_design.sv tb/testbench.sv

        # Run the compiled simulation
        #./obj_dir/Vtestbench    # This should be the name of the generated executable from Verilator

    #- name: Upload simulation logs as artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: simulation-logs
    #    path: ./obj_dir/vltable.log  # This is where Verilator logs are generated
